services:
  app:
    build: .
    container_name: microservice-mindsdb-communication
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8001
    ports:
      - 8001:8001
    volumes:
      - .:/app